$(document).ready(function(){
	$("#report").append($("<div>Hello!</div>"));
	$.getJSON(
		"/rest/collections",
		function(data){
			data.each(function(coll){
				$("#report").append($("<div>"+coll.name+"</div>"));
			});
		}
	);
});